# Generated by Django 5.2.15 on 2026-06-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("said_yes", models.BooleanField(default=False)),
                ("said_yes_at", models.DateTimeField(blank=True, null=True)),
                ("stop_courting", models.BooleanField(default=False)),
                ("stop_courting_reason", models.TextField(blank=True, default="")),
                ("stop_courting_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
