# Generated by Django 5.2.15 on 2026-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="password_hash",
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="site_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Plain text password Kasandra uses to enter the site.",
                max_length=128,
                verbose_name="Site password",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="said_yes",
            field=models.BooleanField(
                default=False,
                help_text="Uncheck to reset — final page will show YES/NO again.",
                verbose_name="Said yes",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="said_yes_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Said yes at"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="stop_courting",
            field=models.BooleanField(
                default=False,
                help_text="Uncheck to reset stop courting state.",
                verbose_name="Stop courting",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="stop_courting_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Stop courting at"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="stop_courting_reason",
            field=models.TextField(
                blank=True, default="", verbose_name="Stop courting reason"
            ),
        ),
    ]
