# Generated by Django 5.2.15 on 2026-06-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_password_to_plain"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="yes_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether the YES notification email was delivered.",
                verbose_name="YES email sent",
            ),
        ),
    ]
